<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <CSweetWorkManagementContractsRepositoryRoot Condition="'$(CSweetWorkManagementContractsRepositoryRoot)' == ''">$(MSBuildThisFileDirectory)..\CSweet.WorkManagement.Contracts</CSweetWorkManagementContractsRepositoryRoot>
    <UseLocalCSweetWorkManagementContracts Condition="'$(UseLocalCSweetWorkManagementContracts)' == '' and Exists('$(CSweetWorkManagementContractsRepositoryRoot)\src\CSweet.WorkManagement.Contracts\CSweet.WorkManagement.Contracts.csproj')">true</UseLocalCSweetWorkManagementContracts>
    <UseLocalCSweetWorkManagementContracts Condition="'$(UseLocalCSweetWorkManagementContracts)' == ''">false</UseLocalCSweetWorkManagementContracts>
  </PropertyGroup>
</Project>
